image:
  file: .gitpod.Dockerfile
ports:
  - port: 8761
  - port: 8680
  - port: 3306
  - port: 5672
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: docker-daemon
    # before: sudo docker-up

  - name: keycloak
    before:
      echo 'Waiting for docker daemon to start' &&
      # while [ ! -S /var/run/docker.sock ]; do sleep 1; done;
    
    init: >-
      export IMAGE="${IMAGE:=quay.io/keycloak/keycloak:12.0.4}" &&
      export KEYCLOAK_USER="${KEYCLOAK_USER:=admin}" &&
      export KEYCLOAK_PASSWORD="${KEYCLOAK_PASSWORD:=password}" &&
      export KEYCLOAK_STATISTICS="${KEYCLOAK_STATISTICS:=all}" &&
      export KEYCLOAK_LOGLEVEL="${KEYCLOAK_LOGLEVEL:=INFO}" &&
      export JAVA_OPTS_APPEND="${JAVA_OPTS_APPEND:=-Dkeycloak.profile.feature.upload_script=enabled -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.account2=enabled -Dkeycloak.profile.feature.account_api=enabled}" &&
      docker-compose up -d &&	docker logs -f keycloak


  - name: rabbitmq
    command: >
      docker run -it 
      --hostname rabbitmq
      -p 5672:5672
      --rm
      --name rabbitmq
      rabbitmq:3.8-management
  
  - name: vault
    command: >-
      wget https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip && 
      unzip vault_1.3.2_linux_amd64.zip && 
      rm -f vault_1.3.2_linux_amd64.zip && 
      chmod +x vault &&
      mv vault /usr/local/bin/ &&
      echo "export VAULT_ADDR=http://127.0.0.1:8200" >> .bashrc

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# check which ports to add

