image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: keycloak
    command: >
      docker run 
      -p 8680:8680 
      -e 
      KEYCLOAK_USER=admin 
      -e 
      KEYCLOAK_PASSWORD=admin
      quay.io/keycloak/keycloak:15.0.2
      -Djboss.http.port=3451
      -b 0.0.0.0 

  - name: rabbitmq
    command: >
      docker run -it 
      --hostname rabbitmq
      -p 5672:5672
      --rm
      --name rabbitmq
      rabbitmq:3.8-management
  
  #- name: hashicorp vault
  #  command: > 
 #     docker run 
 #     --cap-add=IPC_LOCK 
 #     -d 
 #     --name=dev-vault 
 #     vault


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8761
  - port: 8680
  - port: 3306
  - port: 5672
    
