image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

  - name: docker-daemon
    before: sudo docker-up
   
  - name: rabbitmq
    command: >
      docker run 
      --hostname my-rabbit 
      -p 5672:5672 
      --rm  
      --name my-rabbit 
      rabbitmq:3

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
